name: Setup PlantUML
author: Jassiel Ovando

branding:
  icon: image
  color: red

description: Install PlantUML CLI

inputs:
  version:
    description: PlantUML version to install, either a specific version or "latest"
    required: false
    default: "latest"
  java-version:
    description: Java version to use
    required: false
    default: "25"
  java-distribution:
    description: Java distribution to use
    required: false
    default: "temurin"

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.java-distribution }}
        java-package: jre
        java-version: ${{ inputs.java-version }}
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Download PlantUML JAR
      shell: bash
      run: |
        export VERSION="${{ inputs.version }}"
        export INSTALL_DIR="${{ github.workspace }}/.plantuml"
        bash "${{ github.action_path }}/scripts/download.bash"

    - name: Setup wrapper script (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        INSTALL_DIR="${{ github.workspace }}/.plantuml"
        cp "${{ github.action_path }}/scripts/plantuml" "$INSTALL_DIR/plantuml"
        chmod +x "$INSTALL_DIR/plantuml"
        echo "$INSTALL_DIR" >> "$GITHUB_PATH"

    - name: Setup wrapper script (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        INSTALL_DIR="${{ github.workspace }}/.plantuml"
        cp "${{ github.action_path }}/scripts/plantuml.cmd" "$INSTALL_DIR/plantuml.cmd"
        echo "$INSTALL_DIR" >> "$GITHUB_PATH"

    - name: Verify installation
      id: setup
      shell: bash
      run: |
        plantuml --version
        plantuml --check-graphviz

        # Extract version for output
        INSTALLED_VERSION=$(plantuml --version | head -1 | awk '{print $3}')
        echo "version=$INSTALLED_VERSION" >> "$GITHUB_OUTPUT"

outputs:
  version:
    description: The installed PlantUML version
    value: ${{ steps.setup.outputs.version }}
  path:
    description: The path where PlantUML is installed
    value: ${{ github.workspace }}/.plantuml
