name: Setup PlantUML
author: Jassiel Ovando

branding:
  icon: image
  color: red

description: Install PlantUML CLI

inputs:
  version:
    description: PlantUML version to install, either a specific version or "latest"
    required: false
    default: "latest"
  java-version:
    description: Java (JRE) version to use (e.g., 21, 25, or 'latest-lts')
    required: false
    default: "latest-lts"
  java-distribution:
    description: Java distribution to use
    required: false
    default: "temurin"

runs:
  using: composite
  steps:
    - name: Resolve Java version
      id: resolve-java
      shell: bash
      run: |
        JAVA_VERSION="${{ inputs.java-version }}"

        if [ "$JAVA_VERSION" = "latest-lts" ]; then
          echo "Resolving latest LTS version from Adoptium API..."
          JAVA_VERSION=$(curl -s "https://api.adoptium.net/v3/info/available_releases" | \
            jq -r '.available_lts_releases | max')
          echo "Latest LTS version: $JAVA_VERSION"
        fi

        echo "version=$JAVA_VERSION" >> "$GITHUB_OUTPUT"

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.java-distribution }}
        java-package: jre
        java-version: ${{ steps.resolve-java.outputs.version }}

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Download PlantUML JAR
      shell: bash
      run: |
        export VERSION="${{ inputs.version }}"
        export INSTALL_DIR="${{ github.workspace }}/.plantuml"
        bash "${{ github.action_path }}/scripts/download.bash"

    - name: Setup wrapper scripts
      shell: bash
      run: |
        INSTALL_DIR="${{ github.workspace }}/.plantuml"
        ACTION_DIR="${{ github.action_path }}"

        cp "$ACTION_DIR/scripts/plantuml" "$INSTALL_DIR/plantuml"
        chmod +x "$INSTALL_DIR/plantuml"

        if [ "${{ runner.os }}" = "Windows" ]; then
          cp "$ACTION_DIR/scripts/plantuml.cmd" "$INSTALL_DIR/plantuml.cmd"
        fi

        echo "$INSTALL_DIR" >> "$GITHUB_PATH"

    - name: Verify installation and get version
      id: setup
      shell: bash
      run: |
        INSTALLED_VERSION=$(plantuml --version | head -1 | awk '{print $3}')
        echo "version=$INSTALLED_VERSION" >> "$GITHUB_OUTPUT"

outputs:
  version:
    description: The installed PlantUML version
    value: ${{ steps.setup.outputs.version }}
  path:
    description: The path where PlantUML is installed
    value: ${{ github.workspace }}/.plantuml
